import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        // Neo-Minimalist dark palette
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c2c6d7',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#8c90a0',
        'outline-variant': '#424754',
        'surface-tint': '#afc6ff',
        primary: '#afc6ff',
        'on-primary': '#002d6d',
        'primary-container': '#548dff',
        'on-primary-container': '#002760',
        'inverse-primary': '#0058c9',
        secondary: '#ddb7ff',
        'on-secondary': '#490080',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        tertiary: '#4cd7f6',
        'on-tertiary': '#003640',
        'tertiary-container': '#009eb9',
        'on-tertiary-container': '#002f38',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#afc6ff',
        'on-primary-fixed': '#001944',
        'on-primary-fixed-variant': '#00429a',
        'secondary-fixed': '#f0dbff',
        'secondary-fixed-dim': '#ddb7ff',
        'on-secondary-fixed': '#2c0051',
        'on-secondary-fixed-variant': '#6900b3',
        'tertiary-fixed': '#acedff',
        'tertiary-fixed-dim': '#4cd7f6',
        'on-tertiary-fixed': '#001f26',
        'on-tertiary-fixed-variant': '#004e5c',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-variant': '#2d3449',
        foreground: '#dae2fd',
        muted: {
          DEFAULT: '#171f33',
          foreground: '#8c90a0',
        },
        card: {
          DEFAULT: '#171f33',
          foreground: '#dae2fd',
        },
        popover: {
          DEFAULT: '#171f33',
          foreground: '#dae2fd',
        },
        destructive: {
          DEFAULT: '#ffb4ab',
          foreground: '#690005',
        },
        input: '#424754',
        ring: '#afc6ff',
        // Legacy semantic aliases (public-facing components)
        clay: {
          DEFAULT: '#4cd7f6',
          foreground: '#ffffff',
          dark: '#009eb9',
          pale: '#003640',
        },
        cream: {
          100: '#131b2e',
          200: '#0b1326',
          300: '#222a3d',
          400: '#2d3449',
        },
        ink: {
          DEFAULT: '#dae2fd',
          muted: '#c2c6d7',
          faint: '#8c90a0',
          soft: '#c2c6d7',
        },
        border: '#424754',
        'surface-warm': '#171f33',
        'surface-tile': '#060e20',
      },
      fontFamily: {
        display: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        // Legacy typography aliases
        'display-xs': ['20px', { lineHeight: '1.3', fontWeight: '700' }],
        'display-sm': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'display-md': ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-xl': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'hero': ['64px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'caption': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'caption-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'lead': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
        // Legacy radius aliases
        'editorial': '16px',
        'editorial-xs': '8px',
        'editorial-sm': '12px',
        'pill': '9999px',
      },
      spacing: {
        'unit': '4px',
        'container-padding': '24px',
        'gutter': '20px',
        'margin-sm': '16px',
        'margin-md': '32px',
        'margin-lg': '48px',
      },
      maxWidth: {
        'grid': '1280px',
        'reading': '720px',
      },
      padding: {
        'section-sm': '32px',
        'section': '64px',
      },
      boxShadow: {
        'glass': '0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -2px rgba(0, 0, 0, 0.2)',
        'glass-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.3), 0 4px 6px -4px rgba(0, 0, 0, 0.2)',
        'inner-glow': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.1)',
        'primary-glow': '0 0 15px rgba(175, 198, 255, 0.2)',
        'card': '0 1px 3px rgba(0, 0, 0, 0.2), 0 4px 12px rgba(0, 0, 0, 0.3)',
        'card-hover': '0 2px 8px rgba(0, 0, 0, 0.3), 0 12px 32px rgba(0, 0, 0, 0.4)',
        // Legacy shadow aliases
        'elevated': '0 2px 8px rgba(0, 0, 0, 0.3), 0 12px 32px rgba(0, 0, 0, 0.4)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-down': {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-up': 'fade-up 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scale-in 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slide-down 0.2s ease-out',
      },
    },
  },
  plugins: [],
};

export default config;
